// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANtjzEzIGgyI9FM4prKQgjC6KS8vz9xKQ',
    appId: '1:766671517400:web:1baa5dcec34eca143e49ad',
    messagingSenderId: '766671517400',
    projectId: 'movies-recs-22f32',
    authDomain: 'movies-recs-22f32.firebaseapp.com',
    storageBucket: 'movies-recs-22f32.firebasestorage.app',
    measurementId: 'G-K44V4BWHQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-qnxJIfYOVY1ukbuqvPxBAzXYQmAzPNs',
    appId: '1:766671517400:android:a8fc7627821068423e49ad',
    messagingSenderId: '766671517400',
    projectId: 'movies-recs-22f32',
    storageBucket: 'movies-recs-22f32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZKqFm4xyk959KDp8AOxVSKh_c3bqRVCU',
    appId: '1:766671517400:ios:f9acd822cf67b3a93e49ad',
    messagingSenderId: '766671517400',
    projectId: 'movies-recs-22f32',
    storageBucket: 'movies-recs-22f32.firebasestorage.app',
    androidClientId: '766671517400-oov70oitek1smjiqg3ho5cqaobvfs8re.apps.googleusercontent.com',
    iosClientId: '766671517400-uo760ajdf8ipeuv08ijr1p302fqj9uv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZKqFm4xyk959KDp8AOxVSKh_c3bqRVCU',
    appId: '1:766671517400:ios:f9acd822cf67b3a93e49ad',
    messagingSenderId: '766671517400',
    projectId: 'movies-recs-22f32',
    storageBucket: 'movies-recs-22f32.firebasestorage.app',
    androidClientId: '766671517400-oov70oitek1smjiqg3ho5cqaobvfs8re.apps.googleusercontent.com',
    iosClientId: '766671517400-uo760ajdf8ipeuv08ijr1p302fqj9uv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

}